// Shared Claude cost tracking, used by the live note-generation path
// (aiPipeline.js's callAnthropicForNote) and kept as the single source of truth so
// in-memory counters are never split across two independent copies.
const pool = require('../config/db');

// $/token by model. Cache write ~1.25x input rate, cache read ~0.1x input rate —
// applied in trackCost below, not baked into this table.
const MODEL_PRICING = {
  'claude-haiku-4-5-20251001': { input: 1.00 / 1_000_000, output: 5.00 / 1_000_000 },
  'claude-haiku-4-5': { input: 1.00 / 1_000_000, output: 5.00 / 1_000_000 },
  'claude-sonnet-4-6': { input: 3.00 / 1_000_000, output: 15.00 / 1_000_000 },
};
const DEFAULT_MODEL = 'claude-haiku-4-5-20251001';

function resolvePricing(model) {
  return MODEL_PRICING[model] || MODEL_PRICING[DEFAULT_MODEL];
}

// In-memory counters (reset on server restart — a real cap needs the DB-backed
// query too for multi-instance deployments; see getCostStats).
let dailyCost = 0;
let totalCost = 0;
let dailyCallCount = 0;
let totalCallCount = 0;
let lastResetDate = new Date().toISOString().split('T')[0];

const DAILY_COST_LIMIT = parseFloat(process.env.CLAUDE_DAILY_LIMIT || '50.00');
const DAILY_WARNING_THRESHOLD = DAILY_COST_LIMIT * 0.8;
const ENABLE_COST_CAP = process.env.CLAUDE_ENFORCE_CAP === 'true';

const RATE_LIMIT_WINDOW_MS = 60000;
const RATE_LIMIT_MAX_CALLS = parseInt(process.env.CLAUDE_RATE_LIMIT || '150', 10);
let recentCalls = [];

function checkDailyReset() {
  const today = new Date().toISOString().split('T')[0];
  if (today !== lastResetDate) {
    console.log(`[CLAUDE-RESET] New day detected. Yesterday's cost: $${dailyCost.toFixed(4)} (${dailyCallCount} calls)`);
    dailyCost = 0;
    dailyCallCount = 0;
    lastResetDate = today;
  }
}

/**
 * Rate limit — throws if the per-minute call cap is exceeded.
 */
function checkRateLimit() {
  const now = Date.now();
  recentCalls = recentCalls.filter((timestamp) => now - timestamp < RATE_LIMIT_WINDOW_MS);

  if (recentCalls.length >= RATE_LIMIT_MAX_CALLS) {
    const oldestCall = Math.min(...recentCalls);
    const waitMs = RATE_LIMIT_WINDOW_MS - (now - oldestCall);
    throw new Error(
      `Rate limit exceeded: ${recentCalls.length} calls in last minute. ` +
      `Max: ${RATE_LIMIT_MAX_CALLS}/min. Wait ${Math.ceil(waitMs / 1000)}s.`
    );
  }

  recentCalls.push(now);
}

/**
 * Daily cost cap — throws only when CLAUDE_ENFORCE_CAP=true. When disabled (the
 * default), spend is still tracked and logged, just never blocks a note.
 */
function checkCostLimit() {
  checkDailyReset();
  if (ENABLE_COST_CAP && dailyCost >= DAILY_COST_LIMIT) {
    throw new Error(
      `Daily cost limit reached: $${dailyCost.toFixed(4)} >= $${DAILY_COST_LIMIT.toFixed(2)}. ` +
      `Set CLAUDE_DAILY_LIMIT higher or disable with CLAUDE_ENFORCE_CAP=false.`
    );
  }
}

/**
 * Records the cost of one Claude call — updates in-memory counters, logs, and
 * persists to claude_usage_log (best-effort; a DB failure never breaks note
 * generation, since the note was already generated by the time this runs).
 */
async function trackCost(visitId, model, inputTokens, outputTokens, cacheCreationTokens = 0, cacheReadTokens = 0) {
  checkDailyReset();

  const pricing = resolvePricing(model);
  const inputCost = inputTokens * pricing.input;
  const outputCost = outputTokens * pricing.output;
  const cacheCost = cacheCreationTokens * pricing.input; // cache write ~= input rate (conservative; real write is ~1.25x)
  const cacheReadCost = cacheReadTokens * (pricing.input * 0.1); // cache read ~= 10% of input rate

  const callCost = inputCost + outputCost + cacheCost + cacheReadCost;

  dailyCost += callCost;
  totalCost += callCost;
  dailyCallCount++;
  totalCallCount++;

  console.log(
    `[CLAUDE-COST] Visit ${visitId ?? 'unknown'} | Model: ${model} | ` +
    `Call: $${callCost.toFixed(4)} | ` +
    `Daily: $${dailyCost.toFixed(4)} (${dailyCallCount} calls) | ` +
    `Total: $${totalCost.toFixed(4)} (${totalCallCount} calls)`
  );

  if (dailyCost >= DAILY_COST_LIMIT) {
    console.error(
      `❌ CLAUDE DAILY LIMIT REACHED: $${dailyCost.toFixed(4)} >= $${DAILY_COST_LIMIT.toFixed(2)}\n` +
      `   Today: ${dailyCallCount} calls\n` +
      `   ${ENABLE_COST_CAP ? 'Further calls will be blocked (CLAUDE_ENFORCE_CAP=true).' : 'CLAUDE_ENFORCE_CAP is not set — calls are NOT being blocked. Review usage.'}`
    );
  } else if (dailyCost >= DAILY_WARNING_THRESHOLD) {
    console.warn(
      `⚠️  CLAUDE COST WARNING: $${dailyCost.toFixed(4)} (${(dailyCost / DAILY_COST_LIMIT * 100).toFixed(0)}% of $${DAILY_COST_LIMIT.toFixed(2)} daily limit)\n` +
      `   Calls today: ${dailyCallCount} | Remaining budget: $${(DAILY_COST_LIMIT - dailyCost).toFixed(4)}`
    );
  }

  try {
    await pool.query(
      `INSERT INTO claude_usage_log (visit_id, input_tokens, output_tokens,
       cache_creation_tokens, cache_read_tokens, cost, model, created_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())`,
      [visitId ?? null, inputTokens, outputTokens, cacheCreationTokens, cacheReadTokens, callCost, model]
    );
  } catch (err) {
    // Table might not exist yet on an environment that hasn't run the migration —
    // that's a config problem, not a reason to fail a note that already generated.
    if (!String(err?.message || '').includes('does not exist')) {
      console.warn('[Claude] Failed to log usage to database:', err.message);
    }
  }
}

function getCostStats() {
  checkDailyReset();
  return {
    daily: {
      cost: parseFloat(dailyCost.toFixed(6)),
      calls: dailyCallCount,
      limit: DAILY_COST_LIMIT,
      remaining: parseFloat((DAILY_COST_LIMIT - dailyCost).toFixed(6)),
      percentUsed: parseFloat((dailyCost / DAILY_COST_LIMIT * 100).toFixed(2)),
    },
    total: {
      cost: parseFloat(totalCost.toFixed(6)),
      calls: totalCallCount,
    },
    limits: {
      dailyLimit: DAILY_COST_LIMIT,
      warningThreshold: DAILY_WARNING_THRESHOLD,
      enforced: ENABLE_COST_CAP,
      rateLimit: RATE_LIMIT_MAX_CALLS,
    },
    lastReset: lastResetDate,
  };
}

function resetDailyCost() {
  const yesterday = { cost: dailyCost, calls: dailyCallCount, date: lastResetDate };
  dailyCost = 0;
  dailyCallCount = 0;
  lastResetDate = new Date().toISOString().split('T')[0];
  console.log(
    `[CLAUDE-RESET] Manual reset performed\n` +
    `   Previous period: $${yesterday.cost.toFixed(4)} (${yesterday.calls} calls)\n` +
    `   Date: ${yesterday.date}`
  );
  return yesterday;
}

module.exports = {
  checkRateLimit,
  checkCostLimit,
  trackCost,
  getCostStats,
  resetDailyCost,
  MODEL_PRICING,
};
