<#
================================================================================
 enable-eb-cloudwatch-logs.ps1  -  Stream Elastic Beanstalk instance logs to
                                   Amazon CloudWatch Logs
================================================================================
 Pure PowerShell. Works on Windows PowerShell 5.1 and PowerShell 7+.
 ASCII-only on purpose (no em-dashes, no emoji) so it never corrupts on paste.

 THE GOAL:
   Turn on EB "instance log streaming" for the environment 'anot-backend-prod'
   (id e-g7bj3ndsck) so the on-instance logs (eb-engine.log, nginx, the Node app
   stdout, etc.) are shipped to CloudWatch Logs. Once enabled, EB auto-creates
   one log group per streamed file, named:

       /aws/elasticbeanstalk/anot-backend-prod/<full-on-instance-path>

   so eb-engine.log lands in:

       /aws/elasticbeanstalk/anot-backend-prod/var/log/eb-engine.log

   (That group name is GENERATED by EB from the environment name + file path; it
   is not a free-form option you set. This script asserts that exact group shows
   up after the rollout, which is the requirement's "LogGroup" target.)

 HOW EB TURNS THIS ON:
   The single switch is the option setting:
       Namespace : aws:elasticbeanstalk:cloudwatch:logs
       OptionName: StreamLogs   Value: true
   We also set sensible companions in the SAME namespace:
       DeleteOnTerminate = false  (keep logs after instances/env are torn down)
       RetentionInDays   = 90     (auto-expire to control CloudWatch storage cost)

 PERMISSIONS (the "IamFleetRole / CloudWatch Logs permissions" requirement):
   The EC2 instance profile role attached to the environment must be allowed to
   create log groups/streams and put log events, or the CloudWatch Logs agent on
   the instance silently ships nothing. The EB-managed policy
   AWSElasticBeanstalkWebTier already grants this, but to be safe and explicit we
   attach a small inline policy (anot-cloudwatch-logs-prod) scoped to this
   environment's log groups. This is idempotent (put-role-policy overwrites).

 WHAT THIS SCRIPT DOES (top to bottom):
   PRE-FLIGHT  Tooling + identity checks; confirm the environment exists.
   Phase 1     Read the EB config; discover the instance profile + IAM role;
               report the current StreamLogs value.
   Phase 2     Attach CloudWatch Logs permissions to the instance role (inline).
   Phase 3     update-environment to set StreamLogs=true (+ retention) and wait
               for the rollout.
   Phase 4     Poll EB health until Green.
   Phase 5     Verify the eb-engine.log group appears in CloudWatch Logs.

 USAGE:
   pwsh -File scripts/enable-eb-cloudwatch-logs.ps1 -DryRun   # rehearse, no change
   pwsh -File scripts/enable-eb-cloudwatch-logs.ps1           # apply (prompts)
   pwsh -File scripts/enable-eb-cloudwatch-logs.ps1 -Force    # apply, no prompts
   pwsh -File scripts/enable-eb-cloudwatch-logs.ps1 -RetentionInDays 30
================================================================================
#>

[CmdletBinding()]
param(
    [switch]$Force,
    [switch]$SkipConfirm,
    [switch]$DryRun,
    [int]$RetentionInDays = 90,
    [bool]$DeleteOnTerminate = $false
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#region ----------------------------- CONFIG ----------------------------------
$AwsAccountId   = '625242092266'
$Region         = 'ap-southeast-1'
$EbAppName      = 'anot-backend'
$EbEnvName      = 'anot-backend-prod'
$EbEnvId        = 'e-g7bj3ndsck'
$DefaultRole    = 'aws-elasticbeanstalk-ec2-role'   # fallback if discovery fails
$LogsPolicyName = 'anot-cloudwatch-logs-prod'

# The log group EB auto-creates for eb-engine.log once StreamLogs=true. We assert
# this exact name shows up in CloudWatch after the rollout.
$LogGroupPrefix    = "/aws/elasticbeanstalk/$EbEnvName"
$EngineLogGroup    = "$LogGroupPrefix/var/log/eb-engine.log"

$LogsNamespace  = 'aws:elasticbeanstalk:cloudwatch:logs'

$MaxHealthRetries        = 10
$HealthRetryDelaySeconds = 30
$MaxLogRetries           = 12     # log groups can take a couple minutes to appear
$LogRetryDelaySeconds    = 20

$ProjectDir  = Split-Path -Parent $PSScriptRoot
$ArtifactDir = Join-Path $ProjectDir 'dist'

$env:AWS_DEFAULT_REGION = $Region
$env:AWS_PAGER = ''                  # disable the AWS CLI v2 pager (silent-fail source)
$script:CurrentPhase = 'startup'
#endregion

#region --------------------------- HELPERS -----------------------------------
function Write-Phase {
    param([string]$Title)
    $script:CurrentPhase = $Title
    Write-Host ''
    Write-Host ('=' * 78) -ForegroundColor Cyan
    Write-Host "  $Title" -ForegroundColor Cyan
    Write-Host ('=' * 78) -ForegroundColor Cyan
}
function Write-Step { param([string]$Message) Write-Host "  -> $Message" -ForegroundColor Gray }
function Write-Ok   { param([string]$Message) Write-Host "  [OK] $Message" -ForegroundColor Green }
function Write-Warn { param([string]$Message) Write-Host "  [!!] $Message" -ForegroundColor Yellow }
function Write-Diag { param([string]$Message) Write-Host "    $Message" -ForegroundColor DarkGray }

function Confirm-Step {
    param([string]$Message)
    if ($DryRun)                 { Write-Step "[DRY-RUN] would prompt: $Message"; return }
    if ($Force -or $SkipConfirm) { Write-Step "$Message (auto-confirmed)"; return }
    $answer = Read-Host "  ?? $Message  [y/N]"
    if ($answer -notmatch '^(y|yes)$') { throw "Aborted by operator at: $Message" }
}

# Single choke point for every AWS CLI call. Captures stdout and stderr WITHOUT
# corrupting JSON: merges with 2>&1 then splits by object type (stdout = strings,
# stderr = ErrorRecord objects). Temporarily relaxes $ErrorActionPreference so a
# native command writing to stderr (even on exit 0) does not raise a terminating
# NativeCommandError before we read the real exit code. Retries with backoff and,
# on failure, throws a detailed, copy-pasteable diagnostic. -SkipInDryRun marks a
# mutating call (skipped + printed in -DryRun).
function Invoke-Aws {
    [CmdletBinding(PositionalBinding = $false)]
    param(
        [int]$Retries = 1,
        [int]$DelaySeconds = 5,
        [switch]$SkipInDryRun,
        [string]$What,
        [Parameter(ValueFromRemainingArguments = $true)][string[]]$CliArgs
    )

    if (-not $CliArgs -or $CliArgs.Count -eq 0) { throw 'Invoke-Aws called with no AWS CLI arguments.' }
    $cmdText = "aws $($CliArgs -join ' ')"
    $label   = if ($What) { $What } else { $cmdText }

    if ($DryRun -and $SkipInDryRun) {
        Write-Host "    [DRY-RUN] skip mutating call: $cmdText" -ForegroundColor DarkYellow
        return ''
    }

    $attempt = 0
    while ($true) {
        $attempt++
        $prevEap = $ErrorActionPreference
        $ErrorActionPreference = 'Continue'
        try {
            $captured = & aws @CliArgs 2>&1
            $code = $LASTEXITCODE
        }
        catch {
            $code     = 9001
            $captured = $_.Exception.Message
        }
        finally {
            $ErrorActionPreference = $prevEap
        }

        $outParts = @()
        $errParts = @()
        foreach ($item in @($captured)) {
            if ($null -eq $item) { continue }
            if ($item -is [System.Management.Automation.ErrorRecord]) {
                $errParts += $item.ToString()
            } else {
                $outParts += [string]$item
            }
        }
        $stdout = ($outParts -join "`n")
        $stderr = (($errParts -join "`n")).Trim()

        if ($code -eq 0) { return $stdout }

        $lines = @(
            "AWS CLI call FAILED on attempt $attempt of $Retries",
            "  what     : $label",
            "  command  : $cmdText",
            "  region   : $Region",
            "  exit code: $code",
            "  time     : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
        )
        if ($stderr) { $lines += "  aws error: $stderr" }
        else         { $lines += '  aws error: (no stderr output - check credentials / network / pager)' }
        if ($stdout) { $lines += "  aws stdout: $(($stdout -join ' ').Trim())" }
        $detail = ($lines -join "`n")

        if ($attempt -lt $Retries) {
            Write-Warn "$label failed (exit $code); retrying in $DelaySeconds s (attempt $attempt/$Retries)..."
            if ($stderr) { Write-Host "    $stderr" -ForegroundColor DarkRed }
            Start-Sleep -Seconds $DelaySeconds
            continue
        }

        throw $detail
    }
}

# Read the current EB environment object (version/health/status) as a single
# normalized record, or $null if it cannot be read.
function Get-EbEnvironment {
    $json = Invoke-Aws -Retries 3 -DelaySeconds 5 elasticbeanstalk describe-environments `
        --application-name $EbAppName --environment-names $EbEnvName --output json | ConvertFrom-Json
    if (-not $json.Environments -or @($json.Environments).Count -eq 0) { return $null }
    return @($json.Environments)[0]
}

# Poll EB until Health=Green, or until the retry budget is exhausted. Returns the
# final environment object (caller decides success/failure based on Health).
function Wait-ForGreen {
    param(
        [int]$MaxRetries = $MaxHealthRetries,
        [int]$DelaySeconds = $HealthRetryDelaySeconds
    )
    $envNow = Get-EbEnvironment
    if ($null -ne $envNow) {
        Write-Diag "initial: version=$($envNow.VersionLabel)  health=$($envNow.Health)  status=$($envNow.HealthStatus)"
        if ($envNow.Health -eq 'Green') { Write-Ok 'Environment already Green.'; return $envNow }
    }
    for ($i = 1; $i -le $MaxRetries; $i++) {
        Write-Step "Health not Green yet; waiting $DelaySeconds s then re-checking (attempt $i/$MaxRetries)..."
        Start-Sleep -Seconds $DelaySeconds
        $envNow = Get-EbEnvironment
        if ($null -eq $envNow) { Write-Warn 'describe-environments returned no environment; retrying.'; continue }
        Write-Diag "poll $i/${MaxRetries}: version=$($envNow.VersionLabel)  health=$($envNow.Health)  status=$($envNow.HealthStatus)"
        if ($envNow.Health -eq 'Green') { Write-Ok "Environment reached Green after $i poll(s)."; return $envNow }
    }
    return $envNow
}

# Read a single EB option value by namespace+name, normalizing the shapes the
# CLI/ConvertFrom-Json can return (nested arrays, 0/1/many matches) to a clean
# trimmed string or $null.
function Get-EbOption {
    param([object[]]$Options, [string]$Namespace, [string]$Name)
    $found = @($Options | Where-Object { $_.Namespace -eq $Namespace -and $_.OptionName -eq $Name })
    if ($found.Count -eq 0) { return $null }
    $val = $found[0].Value
    while ($val -is [System.Array]) {
        if ($val.Count -eq 0) { return $null }
        $val = $val[0]
    }
    if ($null -eq $val) { return $null }
    $str = ([string]$val).Trim()
    if ([string]::IsNullOrEmpty($str)) { return $null }
    return $str
}
#endregion

# ------------------------------------------------------------------------------
# Failure trap: name the phase, show the underlying error, exit non-zero.
# ------------------------------------------------------------------------------
trap {
    Write-Host ''
    Write-Host ('=' * 78) -ForegroundColor Red
    Write-Host '  ENABLE CLOUDWATCH LOGS FAILED' -ForegroundColor Red
    Write-Host ('=' * 78) -ForegroundColor Red
    Write-Host "  Phase : $script:CurrentPhase" -ForegroundColor Red
    Write-Host "  Time  : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Red
    Write-Host '  Error :' -ForegroundColor Red
    foreach ($l in ("$($_.Exception.Message)" -split "`n")) { Write-Host "    $l" -ForegroundColor Red }
    if ($_.InvocationInfo -and $_.InvocationInfo.PositionMessage) {
        Write-Host '  Where :' -ForegroundColor DarkRed
        foreach ($l in ($_.InvocationInfo.PositionMessage -split "`n")) { Write-Host "    $l" -ForegroundColor DarkRed }
    }
    Write-Host ''
    exit 1
}

# ==============================================================================
# PRE-FLIGHT
# ==============================================================================
Write-Phase 'PRE-FLIGHT: tooling + identity + environment checks'

if ($DryRun) {
    Write-Warn 'DRY-RUN MODE: read-only checks only. No IAM or EB changes will be made.'
} else {
    Write-Step 'LIVE MODE: this run will modify the IAM role policy and the EB environment.'
}

if ($RetentionInDays -le 0) { throw "RetentionInDays must be a positive integer (got $RetentionInDays)." }

Write-Step 'Checking AWS CLI is installed...'
$awsVersion = (& aws --version) 2>&1
if ($LASTEXITCODE -ne 0) { throw 'AWS CLI not found on PATH. Install AWS CLI v2.' }
Write-Step "AWS CLI: $awsVersion"

Write-Step 'Verifying AWS identity (OPERATOR identity, not the app)...'
$identity = Invoke-Aws sts get-caller-identity --output json | ConvertFrom-Json
Write-Step "Authenticated as: $($identity.Arn)"
if ($identity.Account -ne $AwsAccountId) {
    throw "Wrong AWS account: $($identity.Account) (expected $AwsAccountId)."
}

Write-Step "Confirming EB environment '$EbEnvName' ($EbEnvId) exists..."
$envInfo = Invoke-Aws -Retries 3 -DelaySeconds 5 elasticbeanstalk describe-environments `
    --application-name $EbAppName --environment-names $EbEnvName --output json | ConvertFrom-Json
if (-not $envInfo.Environments -or @($envInfo.Environments).Count -eq 0) {
    throw "EB environment '$EbEnvName' not found in application '$EbAppName'."
}
$envObj = @($envInfo.Environments)[0]
Write-Diag "env id : $($envObj.EnvironmentId)"
Write-Diag "version: $($envObj.VersionLabel)  health: $($envObj.Health)  status: $($envObj.HealthStatus)"
if ($envObj.EnvironmentId -ne $EbEnvId) {
    Write-Warn "Environment id is '$($envObj.EnvironmentId)', expected '$EbEnvId'. Proceeding against '$EbEnvName' by name."
}

New-Item -ItemType Directory -Force -Path $ArtifactDir | Out-Null
Write-Ok 'Pre-flight checks passed.'

# ==============================================================================
# PHASE 1 - Read config; discover instance profile + role; report StreamLogs
# ==============================================================================
Write-Phase 'PHASE 1: Read EB config and discover the instance role'

Write-Step 'Reading current EB configuration settings...'
$cfg = Invoke-Aws -Retries 3 -DelaySeconds 5 elasticbeanstalk describe-configuration-settings `
    --application-name $EbAppName --environment-name $EbEnvName --output json | ConvertFrom-Json
$ebOpts = @($cfg.ConfigurationSettings[0].OptionSettings)

$currentStreamLogs = Get-EbOption $ebOpts $LogsNamespace 'StreamLogs'
if ([string]::IsNullOrEmpty($currentStreamLogs)) { $currentStreamLogs = '(unset, default false)' }
$currentRetention  = Get-EbOption $ebOpts $LogsNamespace 'RetentionInDays'
$currentDelete     = Get-EbOption $ebOpts $LogsNamespace 'DeleteOnTerminate'
Write-Diag "current StreamLogs        : $currentStreamLogs"
Write-Diag "current RetentionInDays   : $(if ($currentRetention) {$currentRetention} else {'(unset)'})"
Write-Diag "current DeleteOnTerminate : $(if ($currentDelete) {$currentDelete} else {'(unset)'})"

# Discover the instance profile, then the role behind it (the identity that needs
# CloudWatch Logs permissions). Mirror fix-iam-credentials.ps1's discovery.
$InstanceProfileName = Get-EbOption $ebOpts 'aws:autoscaling:launchconfiguration' 'IamInstanceProfile'
if ([string]::IsNullOrEmpty($InstanceProfileName)) {
    $InstanceProfileName = Get-EbOption $ebOpts 'aws:ec2:instances' 'IamInstanceProfile'
}
if ([string]::IsNullOrEmpty($InstanceProfileName)) {
    Write-Warn "Could not read IamInstanceProfile from the EB config; assuming '$DefaultRole'."
    $InstanceProfileName = $DefaultRole
}
Write-Step "EB instance profile: $InstanceProfileName"

Write-Step 'Resolving the IAM role behind that instance profile...'
$profileJson = Invoke-Aws -Retries 3 -DelaySeconds 5 `
    iam get-instance-profile --instance-profile-name $InstanceProfileName --output json | ConvertFrom-Json
$roles = @($profileJson.InstanceProfile.Roles)
if ($roles.Count -eq 0) {
    throw "Instance profile '$InstanceProfileName' has no role attached. Cannot grant CloudWatch Logs access."
}
$InstanceRole = $roles[0].RoleName
Write-Ok "Instance role: $InstanceRole (this is the identity the CloudWatch agent uses)."

if ($currentStreamLogs -eq 'true') {
    Write-Warn 'StreamLogs is ALREADY true. The script will still (re)assert permissions, retention,'
    Write-Warn 'and verify the log group exists - it is safe to re-run.'
}

# ==============================================================================
# PHASE 2 - Grant the instance role CloudWatch Logs permissions (inline policy)
# ==============================================================================
# The CloudWatch Logs agent on the instance needs to create the log group/stream
# and put events. AWSElasticBeanstalkWebTier already covers this; we add an
# explicit, narrowly-scoped inline policy as a belt-and-suspenders guarantee.
Write-Phase 'PHASE 2: Grant the instance role CloudWatch Logs permissions'

$logGroupArn       = "arn:aws:logs:${Region}:${AwsAccountId}:log-group:${LogGroupPrefix}*"
$logGroupStreamArn = "arn:aws:logs:${Region}:${AwsAccountId}:log-group:${LogGroupPrefix}*:*"

$logsPolicy = [ordered]@{
    Version   = '2012-10-17'
    Statement = @(
        [ordered]@{
            Sid      = 'AnotEbCloudWatchLogs'
            Effect   = 'Allow'
            Action   = @(
                'logs:CreateLogGroup',
                'logs:CreateLogStream',
                'logs:PutLogEvents',
                'logs:DescribeLogStreams',
                'logs:DescribeLogGroups',
                'logs:PutRetentionPolicy',
                'logs:GetLogEvents'
            )
            Resource = @($logGroupArn, $logGroupStreamArn)
        }
    )
}

$logsPolicyFile = Join-Path $ArtifactDir 'anot-cloudwatch-logs-policy.json'
$logsPolicy | ConvertTo-Json -Depth 10 | Out-File -FilePath $logsPolicyFile -Encoding ascii
Write-Step "Wrote CloudWatch Logs policy document to $logsPolicyFile"
Write-Diag "grants on: $LogGroupPrefix* (this environment's log groups only)"

Confirm-Step "Attach inline policy '$LogsPolicyName' (CloudWatch Logs) to role '$InstanceRole'?"
Invoke-Aws -SkipInDryRun -Retries 3 -DelaySeconds 5 -What "iam put-role-policy $LogsPolicyName" `
    iam put-role-policy --role-name $InstanceRole `
    --policy-name $LogsPolicyName --policy-document "file://$logsPolicyFile" | Out-Null
Write-Ok "Instance role '$InstanceRole' can now create/write this environment's CloudWatch log groups."

# ==============================================================================
# PHASE 3 - Enable StreamLogs (+ retention) and wait for the rollout
# ==============================================================================
Write-Phase 'PHASE 3: Enable log streaming to CloudWatch (update-environment)'

$deleteOnTerminateValue = if ($DeleteOnTerminate) { 'true' } else { 'false' }
Write-Step "Target settings in '$LogsNamespace':"
Write-Diag "StreamLogs        = true"
Write-Diag "DeleteOnTerminate = $deleteOnTerminateValue"
Write-Diag "RetentionInDays   = $RetentionInDays"

Confirm-Step "Enable StreamLogs=true (retention ${RetentionInDays}d) on '$EbEnvName' now?"

Invoke-Aws -SkipInDryRun -Retries 3 -DelaySeconds 5 -What 'update-environment (enable StreamLogs)' `
    elasticbeanstalk update-environment `
    --application-name $EbAppName --environment-name $EbEnvName `
    --option-settings `
        "Namespace=$LogsNamespace,OptionName=StreamLogs,Value=true" `
        "Namespace=$LogsNamespace,OptionName=DeleteOnTerminate,Value=$deleteOnTerminateValue" `
        "Namespace=$LogsNamespace,OptionName=RetentionInDays,Value=$RetentionInDays" | Out-Null

if (-not $DryRun) {
    Write-Step 'Waiting for the environment to finish updating...'
    Invoke-Aws -SkipInDryRun elasticbeanstalk wait environment-updated `
        --application-name $EbAppName --environment-names $EbEnvName
    Write-Ok 'EB updated: instance log streaming to CloudWatch is enabled.'
} else {
    Write-Ok '[DRY-RUN] would set StreamLogs=true (+ retention) and wait for the environment update.'
}

# ==============================================================================
# PHASE 4 - Poll EB health until Green
# ==============================================================================
Write-Phase 'PHASE 4: Wait for the environment to stabilize (Green)'

if ($DryRun) {
    Write-Ok '[DRY-RUN] would poll EB health until Green.'
} else {
    Write-Step "Polling EB health until Green (max $MaxHealthRetries x ${HealthRetryDelaySeconds}s)..."
    $envNow = Wait-ForGreen
    $isGreen = ($null -ne $envNow) -and ($envNow.Health -eq 'Green')
    if (-not $isGreen) {
        $finalHealth = if ($envNow) { $envNow.Health } else { '(unknown)' }
        $finalStatus = if ($envNow) { $envNow.HealthStatus } else { '(unknown)' }
        throw "Environment did not reach Green within $MaxHealthRetries retries (health=$finalHealth, status=$finalStatus)."
    }
    Write-Ok "Environment is Green (status: $($envNow.HealthStatus))."
}

# ==============================================================================
# PHASE 5 - Verify the eb-engine.log group appears in CloudWatch Logs
# ==============================================================================
Write-Phase 'PHASE 5: Verify logs appear in CloudWatch'

if ($DryRun) {
    Write-Ok 'DRY-RUN COMPLETE: discovery + permission + option checks validated. No changes were made.'
    Write-Warn 'Re-run without -DryRun to attach the policy and enable StreamLogs.'
    Write-Host ''
    return
}

Write-Step "Looking for log group '$EngineLogGroup' (it can take a couple of minutes to appear)..."
$found = $false
$discovered = @()
for ($i = 1; $i -le $MaxLogRetries; $i++) {
    $raw = Invoke-Aws -Retries 3 -DelaySeconds 5 -What 'logs describe-log-groups' `
        logs describe-log-groups --log-group-name-prefix $LogGroupPrefix --output json
    $groups = @()
    if ($raw) { $groups = @(($raw | ConvertFrom-Json).logGroups) }
    $discovered = @($groups | ForEach-Object { $_.logGroupName })

    if ($discovered -contains $EngineLogGroup) { $found = $true; break }

    if ($discovered.Count -gt 0) {
        Write-Diag "found $($discovered.Count) group(s) under $LogGroupPrefix, but not eb-engine.log yet (attempt $i/$MaxLogRetries)"
    } else {
        Write-Diag "no log groups under $LogGroupPrefix yet (attempt $i/$MaxLogRetries)"
    }
    if ($i -lt $MaxLogRetries) { Start-Sleep -Seconds $LogRetryDelaySeconds }
}

if ($discovered.Count -gt 0) {
    Write-Step "Log groups currently under $LogGroupPrefix :"
    foreach ($g in ($discovered | Sort-Object)) { Write-Host "    $g" -ForegroundColor DarkGray }
}

if (-not $found) {
    Write-Host ''
    Write-Host ('=' * 78) -ForegroundColor Red
    Write-Host '  LOG GROUP NOT FOUND YET' -ForegroundColor Red
    Write-Host ('=' * 78) -ForegroundColor Red
    Write-Warn "StreamLogs is enabled and EB is Green, but '$EngineLogGroup'"
    Write-Warn "has not appeared within $($MaxLogRetries * $LogRetryDelaySeconds)s."
    Write-Warn 'Logs are written when the instance produces output; the group may still appear shortly.'
    Write-Warn 'Check manually with:'
    Write-Diag "aws logs describe-log-groups --log-group-name-prefix $LogGroupPrefix --region $Region"
    Write-Diag "aws logs tail '$EngineLogGroup' --region $Region --since 10m"
    throw "Verification incomplete: '$EngineLogGroup' not found in CloudWatch Logs yet."
}

# ------------------------------------------------------------------------------
# SUCCESS
# ------------------------------------------------------------------------------
Write-Host ''
Write-Host ('=' * 78) -ForegroundColor Green
Write-Host '  SUCCESS: EB instance logs are streaming to CloudWatch Logs' -ForegroundColor Green
Write-Host ('=' * 78) -ForegroundColor Green
Write-Host "  environment : $EbEnvName ($EbEnvId)" -ForegroundColor Green
Write-Host "  StreamLogs  : true  (retention ${RetentionInDays}d, DeleteOnTerminate=$deleteOnTerminateValue)" -ForegroundColor Green
Write-Host "  log group   : $EngineLogGroup" -ForegroundColor Green
Write-Host ''
Write-Host '  Tail the engine log live with:' -ForegroundColor Yellow
Write-Host "    aws logs tail '$EngineLogGroup' --region $Region --follow" -ForegroundColor DarkGray
Write-Host '  List all streamed groups for this environment:' -ForegroundColor Yellow
Write-Host "    aws logs describe-log-groups --log-group-name-prefix $LogGroupPrefix --region $Region" -ForegroundColor DarkGray
Write-Host ''
Write-Ok 'CloudWatch Logs streaming enabled and verified.'
