/**
 * Anot Health baseline load test â€” generated by fix-load-testing.ps1
 * Run: k6 run scripts/load-tests/baseline.js
 */
import http from 'k6/http'
import { check, sleep } from 'k6'

export const options = {
  stages: [
    { duration: '30s', target: 10 },
    { duration: '1m', target: 25 },
    { duration: '30s', target: 0 },
  ],
  thresholds: {
    http_req_duration: ['p(95)<800'],
    http_req_failed: ['rate<0.01'],
  },
}

const BASE = __ENV.API_URL || 'https://api.anot.health'

export default function () {
  const health = http.get(${BASE.replace(/\/+$/, '')}/)
  check(health, {
    'health status 200': (r) => r.status === 200,
    'health latency < 500ms': (r) => r.timings.duration < 500,
  })
  sleep(1)
}