-- Foreign key constraints â€” generated by fix-foreign-keys.ps1
-- Run after validating orphan rows with scripts/validate-fk-integrity.js

BEGIN;

-- visits.clinician_id -> users(id)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_visits_clinician') THEN
    ALTER TABLE visits
      ADD CONSTRAINT fk_visits_clinician
      FOREIGN KEY (clinician_id) REFERENCES users(id) ON DELETE RESTRICT;
  END IF;
END $$;

-- visits.scribe_id -> users(id)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_visits_scribe') THEN
    ALTER TABLE visits
      ADD CONSTRAINT fk_visits_scribe
      FOREIGN KEY (scribe_id) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END $$;

-- notes.submitted_by -> users(id)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notes_submitted_by') THEN
    ALTER TABLE notes
      ADD CONSTRAINT fk_notes_submitted_by
      FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END $$;

-- notes.locked_by -> users(id)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notes_locked_by') THEN
    ALTER TABLE notes
      ADD CONSTRAINT fk_notes_locked_by
      FOREIGN KEY (locked_by) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END $$;

COMMIT;