-- Transcription confidence scores â€” generated by fix-confidence-scores.ps1
ALTER TABLE notes ADD COLUMN IF NOT EXISTS confidence_score NUMERIC(5, 4);
ALTER TABLE notes ADD COLUMN IF NOT EXISTS confidence_scores JSONB;

COMMENT ON COLUMN notes.confidence_score IS 'Overall transcript confidence 0.0000-1.0000 from ASR provider';
COMMENT ON COLUMN notes.confidence_scores IS 'Per-segment confidence array from Deepgram words/channels';