-- User consent tracking â€” generated by fix-user-consent.ps1
CREATE TABLE IF NOT EXISTS user_consents (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  consent_type VARCHAR(64) NOT NULL,
  consent_version VARCHAR(32) NOT NULL,
  granted BOOLEAN NOT NULL DEFAULT false,
  ip_address VARCHAR(64),
  user_agent TEXT,
  granted_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, consent_type, consent_version)
);

CREATE INDEX IF NOT EXISTS idx_user_consents_user ON user_consents (user_id);
CREATE INDEX IF NOT EXISTS idx_user_consents_type ON user_consents (consent_type);