<#
.SYNOPSIS
  ULT audit fix: k6 load testing scripts and baseline performance report.

.EXAMPLE
  powershell -File scripts/fix-load-testing.ps1 -Force
#>

[CmdletBinding()]
param(
    [switch]$Force,
    [switch]$DryRun,
    [switch]$Rollback,
    [string]$ApiUrl = 'https://api.anot.health'
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\fix-common.ps1"
$script:FixForce = $Force
$script:FixDryRun = $DryRun

$ctx = Initialize-FixContext -FixId 'fix-load-testing' -Title 'Load Testing (k6)' `
    -AuditRef 'MEDIUM-LOAD-TEST' -Priority 'MEDIUM'

if ($Rollback) {
    Write-FixPhase 'ROLLBACK: fix-load-testing'
    Restore-FixBackup -FixId 'fix-load-testing'
    exit 0
}

Write-FixPhase $ctx.Title
if (-not (Confirm-FixStep 'Create k6 load test scripts and performance report template?')) { exit 0 }

$k6Script = @"
/**
 * Anot Health baseline load test — generated by fix-load-testing.ps1
 * Run: k6 run scripts/load-tests/baseline.js
 */
import http from 'k6/http'
import { check, sleep } from 'k6'

export const options = {
  stages: [
    { duration: '30s', target: 10 },
    { duration: '1m', target: 25 },
    { duration: '30s', target: 0 },
  ],
  thresholds: {
    http_req_duration: ['p(95)<800'],
    http_req_failed: ['rate<0.01'],
  },
}

const BASE = __ENV.API_URL || '$ApiUrl'

export default function () {
  const health = http.get(`${BASE.replace(/\/+$/, '')}/`)
  check(health, {
    'health status 200': (r) => r.status === 200,
    'health latency < 500ms': (r) => r.timings.duration < 500,
  })
  sleep(1)
}
"@

$k6AuthScript = @'
/**
 * Authenticated API smoke load test (requires K6_EMAIL, K6_PASSWORD, K6_ROLE env vars)
 */
import http from 'k6/http'
import { check, sleep } from 'k6'

const BASE = (__ENV.API_URL || 'https://api.anot.health').replace(/\/+$/, '') + '/api'

export const options = {
  vus: 5,
  duration: '1m',
  thresholds: { http_req_failed: ['rate<0.05'] },
}

export function setup() {
  const res = http.post(`${BASE}/auth/login`, JSON.stringify({
    email: __ENV.K6_EMAIL,
    password: __ENV.K6_PASSWORD,
    role: __ENV.K6_ROLE || 'clinician',
  }), { headers: { 'Content-Type': 'application/json' } })
  const token = res.json('token')
  return { token }
}

export default function (data) {
  const headers = { Authorization: `Bearer ${data.token}` }
  const me = http.get(`${BASE}/auth/me`, { headers })
  check(me, { 'me 200': (r) => r.status === 200 })
  sleep(2)
}
'@

$perfReport = @"
# Load Test Baseline Performance Report

Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
Target API: $ApiUrl

## Test configuration

| Test | VUs | Duration | Threshold |
|------|-----|----------|-----------|
| baseline.js | 0→25→0 | 2 min | p95 < 800ms, errors < 1% |
| auth-smoke.js | 5 | 1 min | errors < 5% |

## How to run

``````bash
# Install k6: https://k6.io/docs/get-started/installation/
k6 run scripts/load-tests/baseline.js
k6 run scripts/load-tests/auth-smoke.js -e API_URL=$ApiUrl -e K6_EMAIL=user@anot.health -e K6_PASSWORD=secret -e K6_ROLE=clinician
``````

## Results (fill after run)

| Metric | Baseline | Target |
|--------|----------|--------|
| p95 latency | _TBD_ | < 800ms |
| Error rate | _TBD_ | < 1% |
| Max RPS | _TBD_ | document |

## Recommendations

- Run baseline weekly against staging before releases.
- Increase VUs gradually to find breaking point.
- Monitor RDS CPU and EB autoscaling during tests.
"@

$loadDir = Join-Path $ctx.Workspace 'scripts\load-tests'
Set-FixFileContent -Path (Join-Path $loadDir 'baseline.js') -Content $k6Script
Set-FixFileContent -Path (Join-Path $loadDir 'auth-smoke.js') -Content $k6AuthScript
Set-FixFileContent -Path (Join-Path $ctx.DistDir 'load-test-performance-report.md') -Content $perfReport

Write-FixReport -Summary 'Created k6 baseline and auth-smoke load tests plus performance report template in dist/load-test-performance-report.md.' -NextSteps @(
    'Install k6 and run: k6 run scripts/load-tests/baseline.js'
    'Record results in dist/load-test-performance-report.md'
)

Write-Host ''
Write-Host '[SUCCESS] fix-load-testing completed' -ForegroundColor Green
