<#
.SYNOPSIS
  ULT audit fix: GitHub Actions CI/CD pipeline (test, deploy, security-scan).

.DESCRIPTION
  Creates .github/workflows/test.yml, deploy.yml, and security-scan.yml at workspace root.
  Includes rollback and change reporting.

.EXAMPLE
  powershell -File scripts/fix-ci-cd-pipeline.ps1 -Force
#>

[CmdletBinding()]
param([switch]$Force, [switch]$DryRun, [switch]$Rollback)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\fix-common.ps1"
$script:FixForce = $Force
$script:FixDryRun = $DryRun

$ctx = Initialize-FixContext -FixId 'fix-ci-cd-pipeline' -Title 'CI/CD Pipeline (GitHub Actions)' `
    -AuditRef 'ULT-0014, ULT-0015' -Priority 'HIGH'

if ($Rollback) {
    Write-FixPhase 'ROLLBACK: fix-ci-cd-pipeline'
    Restore-FixBackup -FixId 'fix-ci-cd-pipeline'
    exit 0
}

Write-FixPhase $ctx.Title
if (-not (Confirm-FixStep 'Create GitHub Actions workflows?')) { exit 0 }

$wfDir = Join-Path $ctx.Workspace '.github\workflows'

$testYml = @'
name: Test

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: anot-backend-main/anot-backend-main
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: anot-backend-main/anot-backend-main/package-lock.json
      - run: npm ci
      - run: npm test --if-present

  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: anot-frontend-main/anot-frontend-main
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: anot-frontend-main/anot-frontend-main/package-lock.json
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm test --if-present
'@

$deployYml = @'
name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Build backend artifact
        working-directory: anot-backend-main/anot-backend-main
        run: |
          npm ci --omit=dev
          echo "Deploy backend via your EB/Railway pipeline here"
      - name: Deployment placeholder
        run: echo "Configure deploy secrets (AWS_EB, RAILWAY_TOKEN) in repo settings"

  deploy-frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build frontend
        working-directory: anot-frontend-main/anot-frontend-main
        run: |
          npm ci
          npm run build
      - name: Deployment placeholder
        run: echo "Configure S3/CloudFront or Vercel deploy step"
'@

$securityYml = @'
name: Security Scan

on:
  schedule:
    - cron: '0 6 * * 1'
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Backend audit
        if: matrix.project == 'backend'
        working-directory: anot-backend-main/anot-backend-main
        run: |
          npm ci
          npm audit --audit-level=high
      - name: Frontend audit
        if: matrix.project == 'frontend'
        working-directory: anot-frontend-main/anot-frontend-main
        run: |
          npm ci
          npm audit --audit-level=high

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
'@

Write-FixPhase 'Creating workflow files'
Set-FixFileContent -Path (Join-Path $wfDir 'test.yml') -Content $testYml
Set-FixFileContent -Path (Join-Path $wfDir 'deploy.yml') -Content $deployYml
Set-FixFileContent -Path (Join-Path $wfDir 'security-scan.yml') -Content $securityYml

$readme = @'
# CI/CD Workflows

Generated by `scripts/fix-ci-cd-pipeline.ps1`.

| Workflow | Trigger | Purpose |
|----------|---------|---------|
| test.yml | PR + push to main | Backend/frontend tests and lint |
| deploy.yml | push to main | Production deploy (configure secrets) |
| security-scan.yml | weekly + PR | npm audit + secret scanning |

Configure repository secrets before enabling deploy steps.
'@
Set-FixFileContent -Path (Join-Path $ctx.Workspace 'docs\audit-fixes\CI-CD.md') -Content $readme

Write-FixReport -Summary 'Created GitHub Actions workflows for automated testing on PR, deployment on main, and weekly security scanning.' -NextSteps @(
    'Add repository secrets for deployment (AWS, Railway, etc.)'
    'Customize deploy.yml with your EB/CloudFront steps'
    'Enable branch protection requiring test.yml to pass'
)

Write-Host ''
Write-Host '[SUCCESS] fix-ci-cd-pipeline completed' -ForegroundColor Green
