<#
.SYNOPSIS
  ULT audit fix: CSRF protection middleware and token validation.

.EXAMPLE
  powershell -File scripts/fix-csrf-protection.ps1 -Force
#>

[CmdletBinding()]
param([switch]$Force, [switch]$DryRun, [switch]$Rollback)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\fix-common.ps1"
$script:FixForce = $Force
$script:FixDryRun = $DryRun

$ctx = Initialize-FixContext -FixId 'fix-csrf-protection' -Title 'CSRF Protection' `
    -AuditRef 'ULT-0005' -Priority 'HIGH'

if ($Rollback) {
    Write-FixPhase 'ROLLBACK: fix-csrf-protection'
    Restore-FixBackup -FixId 'fix-csrf-protection'
    exit 0
}

Write-FixPhase $ctx.Title
Test-RequiredPaths -RequireBackend -RequireFrontend
if (-not (Confirm-FixStep 'Add CSRF middleware and frontend token handling?')) { exit 0 }

$csrfMiddleware = @'
const crypto = require('crypto')

const SAFE_METHODS = new Set(['GET', 'HEAD', 'OPTIONS'])
const TOKEN_HEADER = 'x-csrf-token'
const TOKEN_COOKIE = 'csrf_token'

function generateToken() {
  return crypto.randomBytes(32).toString('hex')
}

function csrfProtection(req, res, next) {
  if (SAFE_METHODS.has(req.method)) {
    if (!req.cookies?.[TOKEN_COOKIE]) {
      const token = generateToken()
      res.cookie(TOKEN_COOKIE, token, {
        httpOnly: false,
        sameSite: 'strict',
        secure: process.env.NODE_ENV === 'production',
        path: '/',
      })
      res.setHeader(TOKEN_HEADER, token)
    }
    return next()
  }

  const cookieToken = req.cookies?.[TOKEN_COOKIE]
  const headerToken = req.get(TOKEN_HEADER)
  if (!cookieToken || !headerToken || cookieToken !== headerToken) {
    return res.status(403).json({ error: 'Invalid or missing CSRF token.' })
  }
  return next()
}

function csrfTokenRoute(req, res) {
  const token = req.cookies?.[TOKEN_COOKIE] || generateToken()
  res.cookie(TOKEN_COOKIE, token, {
    httpOnly: false,
    sameSite: 'strict',
    secure: process.env.NODE_ENV === 'production',
    path: '/',
  })
  res.json({ csrfToken: token })
}

module.exports = { csrfProtection, csrfTokenRoute, TOKEN_HEADER }
'@

$csrfUtilFe = @'
/** CSRF token helper — generated by fix-csrf-protection.ps1 */
let cachedCsrfToken = null

export async function fetchCsrfToken(apiBase) {
  if (cachedCsrfToken) return cachedCsrfToken
  const res = await fetch(`${apiBase.replace(/\/+$/, '')}/csrf-token`, { credentials: 'include' })
  if (!res.ok) throw new Error('Failed to fetch CSRF token')
  const data = await res.json()
  cachedCsrfToken = data.csrfToken
  return cachedCsrfToken
}

export function clearCsrfToken() {
  cachedCsrfToken = null
}

export function getCsrfHeaders(token) {
  return token ? { 'X-CSRF-Token': token } : {}
}
'@

Write-FixPhase 'Backend CSRF middleware'
Set-FixFileContent -Path (Join-Path $ctx.BackendDir 'src\middleware\csrf.js') -Content $csrfMiddleware

$serverPath = Join-Path $ctx.BackendDir 'src\server.js'
if (Test-Path $serverPath) {
    $srv = Get-Content $serverPath -Raw
    if ($srv -notmatch 'cookie-parser') {
        Update-FixFileLine -Path $serverPath -Search "const helmet       = require('helmet')" `
            -Replace "const helmet       = require('helmet')`n  const cookieParser = require('cookie-parser')"
    }
    if ($srv -notmatch 'cookieParser\(\)') {
        Update-FixFileLine -Path $serverPath -Search 'app.use(cors(corsOptions))' `
            -Replace "app.use(cookieParser())`napp.use(cors(corsOptions))"
    }
    Invoke-ServerPatch -Marker 'csrfProtection' -InsertAfter "app.use(loggingMiddleware)" `
        -PatchBlock @"
const { csrfProtection, csrfTokenRoute } = require('./middleware/csrf')
app.get('/api/csrf-token', csrfTokenRoute)
app.use('/api', csrfProtection)
"@
}

$bePkg = Join-Path $ctx.BackendDir 'package.json'
if (Test-Path $bePkg) {
    $pkg = Get-Content $bePkg -Raw | ConvertFrom-Json
    if (-not $pkg.dependencies) {
        $pkg | Add-Member -NotePropertyName 'dependencies' -NotePropertyValue ([pscustomobject]@{}) -Force
    }
    $depNames = @($pkg.dependencies.PSObject.Properties | ForEach-Object { $_.Name })
    if ($depNames -notcontains 'cookie-parser') {
        $pkg.dependencies | Add-Member -NotePropertyName 'cookie-parser' -NotePropertyValue '^1.4.7' -Force
        Set-FixFileContent -Path $bePkg -Content ($pkg | ConvertTo-Json -Depth 10) -ForceWrite
    } else {
        Write-FixStep 'cookie-parser already listed in package.json'
    }
}

Write-FixPhase 'Frontend CSRF helper'
Set-FixFileContent -Path (Join-Path $ctx.FrontendDir 'src\utils\csrf.js') -Content $csrfUtilFe

Write-FixReport -Summary 'Added double-submit CSRF protection: cookie + X-CSRF-Token header on state-changing API requests, plus /api/csrf-token endpoint and frontend helper.' -NextSteps @(
    'Run npm install cookie-parser in backend'
    'Wire fetchCsrfToken into api.js buildRequestHeaders for POST/PUT/DELETE'
    'Ensure CORS credentials: true on frontend fetch calls'
)

Write-Host ''
Write-Host '[SUCCESS] fix-csrf-protection completed' -ForegroundColor Green
