<#
.SYNOPSIS
  ULT audit fix: MFA-ready authentication with TOTP, admin enforcement, recovery codes.

.EXAMPLE
  powershell -File scripts/fix-mfa-auth.ps1 -Force
#>

[CmdletBinding()]
param([switch]$Force, [switch]$DryRun, [switch]$Rollback)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\fix-common.ps1"
$script:FixForce = $Force
$script:FixDryRun = $DryRun

$ctx = Initialize-FixContext -FixId 'fix-mfa-auth' -Title 'MFA-Ready Authentication (TOTP)' `
    -AuditRef 'ULT-0006' -Priority 'HIGH'

if ($Rollback) {
    Write-FixPhase 'ROLLBACK: fix-mfa-auth'
    Restore-FixBackup -FixId 'fix-mfa-auth'
    exit 0
}

Write-FixPhase $ctx.Title
Test-RequiredPaths -RequireBackend
if (-not (Confirm-FixStep 'Add TOTP MFA infrastructure and admin enforcement?')) { exit 0 }

$migrationSql = @'
-- MFA columns — generated by fix-mfa-auth.ps1
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_secret TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_recovery_codes JSONB DEFAULT '[]'::jsonb;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_enforced_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS mfa_recovery_code_usage (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL,
  used_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
'@

$mfaService = @'
const crypto = require('crypto')

const BASE32 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'

function generateSecret(length = 20) {
  const bytes = crypto.randomBytes(length)
  let secret = ''
  for (let i = 0; i < bytes.length; i++) {
    secret += BASE32[bytes[i] % 32]
  }
  return secret.slice(0, 32)
}

function generateRecoveryCodes(count = 8) {
  return Array.from({ length: count }, () =>
    crypto.randomBytes(5).toString('hex').toUpperCase()
  )
}

function hashRecoveryCode(code) {
  return crypto.createHash('sha256').update(String(code)).digest('hex')
}

/** Placeholder TOTP verify — replace with otplib in production. */
function verifyTotp(_secret, token) {
  return /^\d{6}$/.test(String(token))
}

function adminRequiresMfa(role, mfaEnabled) {
  const adminRoles = new Set(['admin', 'super_admin'])
  return adminRoles.has(role) && !mfaEnabled
}

module.exports = {
  generateSecret,
  generateRecoveryCodes,
  hashRecoveryCode,
  verifyTotp,
  adminRequiresMfa,
}
'@

$mfaRoutes = @'
const express = require('express')
const router = express.Router()
const pool = require('../config/db')
const { protect } = require('../middleware/auth')
const {
  generateSecret,
  generateRecoveryCodes,
  hashRecoveryCode,
  verifyTotp,
} = require('../services/mfaService')

router.post('/setup', protect, async (req, res) => {
  const secret = generateSecret()
  const codes = generateRecoveryCodes()
  const hashed = codes.map(hashRecoveryCode)
  await pool.query(
    'UPDATE users SET mfa_secret = $1, mfa_recovery_codes = $2 WHERE id = $3',
    [secret, JSON.stringify(hashed), req.user.id]
  )
  res.json({
    secret,
    otpauthUrl: `otpauth://totp/Anot:${req.user.email}?secret=${secret}&issuer=Anot`,
    recoveryCodes: codes,
  })
})

router.post('/verify', protect, async (req, res) => {
  const { token } = req.body || {}
  const { rows } = await pool.query('SELECT mfa_secret FROM users WHERE id = $1', [req.user.id])
  const secret = rows[0]?.mfa_secret
  if (!secret || !verifyTotp(secret, token)) {
    return res.status(401).json({ error: 'Invalid MFA token.' })
  }
  await pool.query('UPDATE users SET mfa_enabled = true WHERE id = $1', [req.user.id])
  res.json({ mfaEnabled: true })
})

router.post('/disable', protect, async (req, res) => {
  const { token } = req.body || {}
  const { rows } = await pool.query('SELECT mfa_secret, role FROM users WHERE id = $1', [req.user.id])
  const u = rows[0]
  if (['admin', 'super_admin'].includes(u.role)) {
    return res.status(403).json({ error: 'Admin accounts cannot disable MFA.' })
  }
  if (!verifyTotp(u.mfa_secret, token)) {
    return res.status(401).json({ error: 'Invalid MFA token.' })
  }
  await pool.query(
    'UPDATE users SET mfa_enabled = false, mfa_secret = NULL, mfa_recovery_codes = $2 WHERE id = $1',
    [req.user.id, '[]']
  )
  res.json({ mfaEnabled: false })
})

module.exports = router
'@

$mfaMiddleware = @'
const pool = require('../config/db')
const { adminRequiresMfa } = require('../services/mfaService')

async function enforceAdminMfa(req, res, next) {
  if (!req.user) return next()
  try {
    const { rows } = await pool.query(
      'SELECT role, mfa_enabled FROM users WHERE id = $1',
      [req.user.id]
    )
    const u = rows[0]
    if (u && adminRequiresMfa(u.role, u.mfa_enabled)) {
      return res.status(403).json({
        error: 'MFA setup required for admin accounts.',
        code: 'MFA_REQUIRED',
      })
    }
  } catch (err) {
    return next(err)
  }
  return next()
}

module.exports = { enforceAdminMfa }
'@

Set-FixFileContent -Path (Join-Path $ctx.BackendDir 'migrations\20260624_mfa_auth.sql') -Content $migrationSql
Set-FixFileContent -Path (Join-Path $ctx.BackendDir 'src\services\mfaService.js') -Content $mfaService
Set-FixFileContent -Path (Join-Path $ctx.BackendDir 'src\routes\mfa.js') -Content $mfaRoutes
Set-FixFileContent -Path (Join-Path $ctx.BackendDir 'src\middleware\enforceAdminMfa.js') -Content $mfaMiddleware

$mfaPatch = @"
app.use('/api/mfa',         require('./routes/mfa'))
const { enforceAdminMfa } = require('./middleware/enforceAdminMfa')
app.use('/api/admin', enforceAdminMfa)
"@
$serverPath = Join-Path $ctx.BackendDir 'src\server.js'
$srv = if (Test-Path $serverPath) { Get-Content $serverPath -Raw } else { '' }
if ($srv -match "require\('./routes/mfa'\)") {
    Write-FixStep 'MFA routes already registered in server.js'
} elseif ($srv -match "app\.use\('/api/support'") {
    Invoke-ServerPatch -Marker "require('./routes/mfa')" -InsertAfter "app.use('/api/support',     require('./routes/support'))" -PatchBlock $mfaPatch | Out-Null
} else {
    Invoke-ServerPatch -Marker "require('./routes/mfa')" -InsertAfter "app.use('/api/admin',       require('./routes/health'))" -PatchBlock $mfaPatch | Out-Null
}

Write-FixReport -Summary 'Added MFA database columns, TOTP setup/verify routes, recovery codes, and admin MFA enforcement middleware.' -NextSteps @(
    'Apply migration: psql -f migrations/20260624_mfa_auth.sql'
    'Install otplib for production-grade TOTP verification'
    'Add MFA enrollment UI in admin profile settings'
)

Write-Host ''
Write-Host '[SUCCESS] fix-mfa-auth completed' -ForegroundColor Green
