<#
.SYNOPSIS
  ULT audit fix: Add foreign key constraints migration with integrity validation.

.EXAMPLE
  powershell -File scripts/fix-foreign-keys.ps1 -Force
#>

[CmdletBinding()]
param([switch]$Force, [switch]$DryRun, [switch]$Rollback)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\fix-common.ps1"
$script:FixForce = $Force
$script:FixDryRun = $DryRun

$ctx = Initialize-FixContext -FixId 'fix-foreign-keys' -Title 'Foreign Key Constraints' `
    -AuditRef 'ULT-0008' -Priority 'HIGH'

if ($Rollback) {
    Write-FixPhase 'ROLLBACK: fix-foreign-keys'
    Restore-FixBackup -FixId 'fix-foreign-keys'
    exit 0
}

Write-FixPhase $ctx.Title
Test-RequiredPaths -RequireBackend
if (-not (Confirm-FixStep 'Create FK migration and validation script?')) { exit 0 }

$migrationSql = @'
-- Foreign key constraints — generated by fix-foreign-keys.ps1
-- Run after validating orphan rows with scripts/validate-fk-integrity.js

BEGIN;

-- visits.clinician_id -> users(id)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_visits_clinician') THEN
    ALTER TABLE visits
      ADD CONSTRAINT fk_visits_clinician
      FOREIGN KEY (clinician_id) REFERENCES users(id) ON DELETE RESTRICT;
  END IF;
END $$;

-- visits.scribe_id -> users(id)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_visits_scribe') THEN
    ALTER TABLE visits
      ADD CONSTRAINT fk_visits_scribe
      FOREIGN KEY (scribe_id) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END $$;

-- notes.submitted_by -> users(id)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notes_submitted_by') THEN
    ALTER TABLE notes
      ADD CONSTRAINT fk_notes_submitted_by
      FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END $$;

-- notes.locked_by -> users(id)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notes_locked_by') THEN
    ALTER TABLE notes
      ADD CONSTRAINT fk_notes_locked_by
      FOREIGN KEY (locked_by) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END $$;

COMMIT;
'@

$rollbackSql = @'
-- Rollback FK constraints added by fix-foreign-keys.ps1
ALTER TABLE visits DROP CONSTRAINT IF EXISTS fk_visits_clinician;
ALTER TABLE visits DROP CONSTRAINT IF EXISTS fk_visits_scribe;
ALTER TABLE notes DROP CONSTRAINT IF EXISTS fk_notes_submitted_by;
ALTER TABLE notes DROP CONSTRAINT IF EXISTS fk_notes_locked_by;
'@

$validateJs = @'
/**
 * Validate referential integrity before applying FK migration.
 * Usage: node scripts/validate-fk-integrity.js
 */
require('dotenv').config()
const pool = require('../src/config/db').pool || require('../src/config/db')

const checks = [
  { name: 'visits.clinician_id orphans', sql: `SELECT COUNT(*) AS n FROM visits v LEFT JOIN users u ON v.clinician_id = u.id WHERE u.id IS NULL` },
  { name: 'visits.scribe_id orphans', sql: `SELECT COUNT(*) AS n FROM visits v LEFT JOIN users u ON v.scribe_id = u.id WHERE v.scribe_id IS NOT NULL AND u.id IS NULL` },
  { name: 'notes.submitted_by orphans', sql: `SELECT COUNT(*) AS n FROM notes n LEFT JOIN users u ON n.submitted_by = u.id WHERE n.submitted_by IS NOT NULL AND u.id IS NULL` },
]

async function main() {
  let failed = false
  for (const c of checks) {
    const { rows } = await pool.query(c.sql)
    const n = parseInt(rows[0].n, 10)
    console.log(`${c.name}: ${n}`)
    if (n > 0) failed = true
  }
  process.exit(failed ? 1 : 0)
}

main().catch((e) => { console.error(e); process.exit(1) })
'@

$migDir = Join-Path $ctx.BackendDir 'migrations'
Set-FixFileContent -Path (Join-Path $migDir '20260624_foreign_key_constraints.sql') -Content $migrationSql
Set-FixFileContent -Path (Join-Path $migDir '20260624_foreign_key_constraints_rollback.sql') -Content $rollbackSql
Set-FixFileContent -Path (Join-Path $ctx.BackendDir 'scripts\validate-fk-integrity.js') -Content $validateJs

Write-FixReport -Summary 'Created FK migration SQL with idempotent DO blocks, rollback SQL, and Node validation script for orphan detection.' -NextSteps @(
    'Run: node scripts/validate-fk-integrity.js (must exit 0)'
    'Apply: psql -f migrations/20260624_foreign_key_constraints.sql'
    'Rollback: psql -f migrations/20260624_foreign_key_constraints_rollback.sql'
)

Write-Host ''
Write-Host '[SUCCESS] fix-foreign-keys completed' -ForegroundColor Green
