<#
.SYNOPSIS
  ULT audit fix: Landscape orientation CSS media queries for mobile portals.

.EXAMPLE
  powershell -File scripts/fix-landscape-css.ps1 -Force
#>

[CmdletBinding()]
param([switch]$Force, [switch]$DryRun, [switch]$Rollback)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\fix-common.ps1"
$script:FixForce = $Force
$script:FixDryRun = $DryRun

$ctx = Initialize-FixContext -FixId 'fix-landscape-css' -Title 'Landscape Orientation CSS' `
    -AuditRef 'MEDIUM-LANDSCAPE' -Priority 'MEDIUM'

if ($Rollback) {
    Write-FixPhase 'ROLLBACK: fix-landscape-css'
    Restore-FixBackup -FixId 'fix-landscape-css'
    exit 0
}

Write-FixPhase $ctx.Title
Test-RequiredPaths -RequireFrontend
if (-not (Confirm-FixStep 'Add landscape-specific CSS media queries?')) { exit 0 }

$landscapeCss = @'
/**
 * Landscape orientation fixes — generated by fix-landscape-css.ps1
 * Targets phones/tablets in landscape where vertical space is limited.
 */

@media screen and (orientation: landscape) and (max-height: 500px) {
  .portal-sidebar,
  .sidebar,
  [class*='sidebar'] {
    max-height: 100vh;
    overflow-y: auto;
  }

  .portal-header,
  .adm-header,
  [class*='header'] {
    padding-top: 0.25rem;
    padding-bottom: 0.25rem;
  }

  .sf-note-panel,
  .clinician-main,
  .scribe-workspace {
    max-height: calc(100vh - 56px);
    overflow-y: auto;
  }

  .modal-overlay,
  .portal-modal {
    align-items: flex-start;
    padding-top: 0.5rem;
  }

  .login-card {
    max-height: 90vh;
    overflow-y: auto;
  }
}

@media screen and (orientation: landscape) and (min-width: 768px) and (max-height: 600px) {
  .portal-grid {
    grid-template-columns: 200px 1fr;
  }

  .adm-form-card {
    max-height: calc(100vh - 120px);
    overflow-y: auto;
  }
}
'@

$cssPath = Join-Path $ctx.FrontendDir 'src\pages\landscape-orientation.css'
Set-FixFileContent -Path $cssPath -Content $landscapeCss

$mainJsx = Join-Path $ctx.FrontendDir 'src\main.jsx'
if (Test-Path $mainJsx) {
    Update-FixFileLine -Path $mainJsx -Search "import './index.css'" `
        -Replace "import './index.css'`nimport './pages/landscape-orientation.css'" -NotContainsSkip
}

$indexCss = Join-Path $ctx.FrontendDir 'src\index.css'
if (Test-Path $indexCss) {
    $idx = Get-Content $indexCss -Raw
    if ($idx -notmatch 'landscape-orientation') {
        Update-FixFileLine -Path $indexCss -Search '/* mobile-responsive-patch imported in main */' `
            -Replace "/* mobile-responsive-patch imported in main */`n@import url('./pages/landscape-orientation.css');" -NotContainsSkip
    }
}

Write-FixPhase 'Scanning existing landscape rules'
$existing = Get-ChildItem -Path (Join-Path $ctx.FrontendDir 'src') -Recurse -Filter *.css |
    Select-String -Pattern 'orientation:\s*landscape' -SimpleMatch
Write-FixStep "Existing landscape rules: $(@($existing).Count)"

$report = @"
# Landscape CSS Audit

Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

## Before
- Dedicated landscape stylesheet: missing
- Existing landscape media queries in src/: $(@($existing).Count)

## After
- Added ``src/pages/landscape-orientation.css``
- Imported in ``src/main.jsx``

## Test viewports
| Device | Size | Orientation |
|--------|------|-------------|
| iPhone SE | 667x375 | landscape |
| iPad | 1024x768 | landscape |
| Android phone | 780x360 | landscape |

Use browser DevTools device toolbar to verify sidebar scroll and modal positioning.
"@
Set-FixFileContent -Path (Join-Path $ctx.DistDir 'landscape-css-report.md') -Content $report

Write-FixReport -Summary 'Added landscape-orientation.css with max-height landscape rules for sidebars, modals, and note panels; imported in main.jsx.' -NextSteps @(
    'Test Clinician and Scribe dashboards at 667x375 landscape'
    'Adjust class selectors if layout components use different names'
)

Write-Host ''
Write-Host '[SUCCESS] fix-landscape-css completed' -ForegroundColor Green
