<#
.SYNOPSIS
  ULT audit fix: Unit tests (backend + frontend) — Jest/Vitest config and sample tests.

.DESCRIPTION
  Creates Jest configuration and sample tests for backend (src/__tests__/) and
  Vitest configuration for frontend (src/__tests__/). Targets 70%+ coverage thresholds.
  Generates change report with before/after previews and rollback support.

.PARAMETER Force
  Apply changes without confirmation prompts.

.PARAMETER DryRun
  Preview changes only; no files written.

.PARAMETER Rollback
  Restore files from the latest backup manifest.

.EXAMPLE
  powershell -File scripts/fix-unit-tests.ps1 -Force
#>

[CmdletBinding()]
param([switch]$Force, [switch]$DryRun, [switch]$Rollback)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\fix-common.ps1"
$script:FixForce = $Force
$script:FixDryRun = $DryRun

$ctx = Initialize-FixContext -FixId 'fix-unit-tests' -Title 'Unit Tests (Backend + Frontend)' `
    -AuditRef 'ULT-0003, ULT-0004, ULT-0012, ULT-0013' -Priority 'HIGH'

if ($Rollback) {
    Write-FixPhase 'ROLLBACK: fix-unit-tests'
    Restore-FixBackup -FixId 'fix-unit-tests'
    exit 0
}

Write-FixPhase $ctx.Title
Test-RequiredPaths -RequireBackend -RequireFrontend

if (-not (Confirm-FixStep 'Create Jest/Vitest test structure and sample tests?')) { exit 0 }

$be = $ctx.BackendDir
$fe = $ctx.FrontendDir

# --- Backend Jest ---
$beJestConfig = @'
/** Jest config — generated by fix-unit-tests.ps1 */
module.exports = {
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.test.js'],
  collectCoverageFrom: [
    'src/**/*.js',
    '!src/**/__tests__/**',
    '!src/server.js',
  ],
  coverageThreshold: {
    global: { branches: 70, functions: 70, lines: 70, statements: 70 },
  },
  coverageDirectory: 'coverage',
  verbose: true,
}
'@

$beHealthTest = @'
describe('health utilities', () => {
  it('returns healthy status shape', () => {
    const payload = { message: 'Anot API is running', version: 'v42', status: 'healthy' }
    expect(payload.status).toBe('healthy')
    expect(payload.message).toContain('Anot')
  })
})
'@

$bePasswordTest = @'
const { validatePassword } = require('../utils/passwordPolicy')

describe('passwordPolicy', () => {
  it('rejects short passwords', () => {
    const result = validatePassword('abc')
    expect(result.valid).toBe(false)
  })

  it('accepts strong passwords', () => {
    const result = validatePassword('Password@2026!')
    expect(result.valid).toBe(true)
  })
})
'@

$bePackageScripts = @{
    test = 'jest --coverage'
    'test:watch' = 'jest --watch'
}

# --- Frontend Vitest ---
$feVitestConfig = @'
import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    include: ['src/**/__tests__/**/*.{test,spec}.{js,jsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      thresholds: { lines: 70, functions: 70, branches: 70, statements: 70 },
    },
  },
})
'@

$feAppTest = @'
import { describe, it, expect } from 'vitest'

describe('App smoke', () => {
  it('sanity check for test runner', () => {
    expect(true).toBe(true)
  })
})
'@

$feApiTest = @'
import { describe, it, expect } from 'vitest'
import { isAbortError, isLikelyNetworkFailure } from '../services/api'

describe('api helpers', () => {
  it('detects AbortError', () => {
    expect(isAbortError({ name: 'AbortError' })).toBe(true)
    expect(isAbortError(new Error('other'))).toBe(false)
  })

  it('detects network failures', () => {
    expect(isLikelyNetworkFailure({ name: 'TypeError', message: 'Failed to fetch' })).toBe(true)
  })
})
'@

Write-FixPhase 'Backend: Jest configuration and tests'
Set-FixFileContent -Path (Join-Path $be 'jest.config.js') -Content $beJestConfig
Set-FixFileContent -Path (Join-Path $be 'src\__tests__\health.test.js') -Content $beHealthTest
Set-FixFileContent -Path (Join-Path $be 'src\__tests__\passwordPolicy.test.js') -Content $bePasswordTest

$bePkgPath = Join-Path $be 'package.json'
if (Test-Path $bePkgPath) {
    $bePkg = Get-Content $bePkgPath -Raw | ConvertFrom-Json
    if (-not ($bePkg.scripts.PSObject.Properties.Name -contains 'test')) {
        $bePkg.scripts | Add-Member -NotePropertyName 'test' -NotePropertyValue 'jest --coverage' -Force
    }
    if (-not ($bePkg.scripts.PSObject.Properties.Name -contains 'test:watch')) {
        $bePkg.scripts | Add-Member -NotePropertyName 'test:watch' -NotePropertyValue 'jest --watch' -Force
    }
    if (-not ($bePkg.devDependencies.PSObject.Properties.Name -contains 'jest')) {
        $bePkg.devDependencies | Add-Member -NotePropertyName 'jest' -NotePropertyValue '^29.7.0' -Force
    }
    Set-FixFileContent -Path $bePkgPath -Content ($bePkg | ConvertTo-Json -Depth 10) -ForceWrite
}

Write-FixPhase 'Frontend: Vitest configuration and tests'
Set-FixFileContent -Path (Join-Path $fe 'vitest.config.js') -Content $feVitestConfig
Set-FixFileContent -Path (Join-Path $fe 'src\__tests__\App.test.jsx') -Content $feAppTest
Set-FixFileContent -Path (Join-Path $fe 'src\__tests__\api.test.js') -Content $feApiTest

$fePkgPath = Join-Path $fe 'package.json'
if (Test-Path $fePkgPath) {
    $fePkg = Get-Content $fePkgPath -Raw | ConvertFrom-Json
    if (-not ($fePkg.scripts.PSObject.Properties.Name -contains 'test')) {
        $fePkg.scripts | Add-Member -NotePropertyName 'test' -NotePropertyValue 'vitest run --coverage' -Force
    }
    if (-not ($fePkg.devDependencies.PSObject.Properties.Name -contains 'vitest')) {
        $fePkg.devDependencies | Add-Member -NotePropertyName 'vitest' -NotePropertyValue '^3.0.0' -Force
    }
    if (-not ($fePkg.devDependencies.PSObject.Properties.Name -contains '@vitest/coverage-v8')) {
        $fePkg.devDependencies | Add-Member -NotePropertyName '@vitest/coverage-v8' -NotePropertyValue '^3.0.0' -Force
    }
    if (-not ($fePkg.devDependencies.PSObject.Properties.Name -contains 'jsdom')) {
        $fePkg.devDependencies | Add-Member -NotePropertyName 'jsdom' -NotePropertyValue '^26.0.0' -Force
    }
    Set-FixFileContent -Path $fePkgPath -Content ($fePkg | ConvertTo-Json -Depth 10) -ForceWrite
}

Write-FixReport -Summary 'Added Jest (backend) and Vitest (frontend) test scaffolding with 70% coverage thresholds and sample unit tests.' -NextSteps @(
    'Run: cd anot-backend-main/anot-backend-main && npm install && npm test'
    'Run: cd anot-frontend-main/anot-frontend-main && npm install && npm test'
    'Expand test suites to reach 70%+ coverage on critical paths'
)

Write-Host ''
Write-Host '[SUCCESS] fix-unit-tests completed' -ForegroundColor Green
