<#
.SYNOPSIS
  ULT audit fix: OpenAPI/Swagger documentation and API.md guide.

.EXAMPLE
  powershell -File scripts/fix-api-documentation.ps1 -Force
#>

[CmdletBinding()]
param([switch]$Force, [switch]$DryRun, [switch]$Rollback)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\fix-common.ps1"
$script:FixForce = $Force
$script:FixDryRun = $DryRun

$ctx = Initialize-FixContext -FixId 'fix-api-documentation' -Title 'API Documentation (OpenAPI)' `
    -AuditRef 'MEDIUM-API-DOC' -Priority 'MEDIUM'

if ($Rollback) {
    Write-FixPhase 'ROLLBACK: fix-api-documentation'
    Restore-FixBackup -FixId 'fix-api-documentation'
    exit 0
}

Write-FixPhase $ctx.Title
Test-RequiredPaths -RequireBackend
if (-not (Confirm-FixStep 'Generate OpenAPI spec and API.md guide?')) { exit 0 }

$openApiYaml = @'
openapi: 3.0.3
info:
  title: Anot Health API
  version: 1.42.0
  description: Clinical documentation platform API
servers:
  - url: https://api.anot.health/api
    description: Production
  - url: http://127.0.0.1:5000/api
    description: Local development
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /auth/login:
    post:
      summary: Authenticate user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, role]
              properties:
                email: { type: string, format: email }
                password: { type: string }
                role: { type: string }
      responses:
        '200': { description: JWT token returned }
        '401': { description: Invalid credentials }
  /auth/me:
    get:
      summary: Current user profile
      tags: [Auth]
      security: [{ bearerAuth: [] }]
      responses:
        '200': { description: User object }
  /patients:
    get:
      summary: List patients
      tags: [Patients]
      security: [{ bearerAuth: [] }]
      responses:
        '200': { description: Patient list }
    post:
      summary: Create patient
      tags: [Patients]
      security: [{ bearerAuth: [] }]
      responses:
        '201': { description: Patient created }
  /visits:
    get:
      summary: List visits
      tags: [Visits]
      security: [{ bearerAuth: [] }]
      responses:
        '200': { description: Visit list }
  /visits/{id}/transcribe:
    post:
      summary: Trigger transcription
      tags: [Visits]
      security: [{ bearerAuth: [] }]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        '202': { description: Transcription queued }
  /notes/{id}:
    get:
      summary: Get note by ID
      tags: [Notes]
      security: [{ bearerAuth: [] }]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        '200': { description: Note with transcription }
  /csrf-token:
    get:
      summary: Obtain CSRF token
      tags: [Security]
      responses:
        '200': { description: CSRF token }
'@

$swaggerRoute = @'
const express = require('express')
const fs = require('fs')
const path = require('path')
const router = express.Router()

router.get('/openapi.yaml', (req, res) => {
  const specPath = path.join(__dirname, '../../docs/openapi.yaml')
  if (!fs.existsSync(specPath)) {
    return res.status(404).json({ error: 'OpenAPI spec not found.' })
  }
  res.type('text/yaml').send(fs.readFileSync(specPath, 'utf8'))
})

router.get('/docs', (req, res) => {
  res.redirect('https://editor.swagger.io/?url=' + encodeURIComponent(`${req.protocol}://${req.get('host')}/api/openapi.yaml`))
})

module.exports = router
'@

$apiMd = @'
# Anot Health API Guide

Generated by `scripts/fix-api-documentation.ps1`.

## Base URLs

| Environment | URL |
|-------------|-----|
| Production | `https://api.anot.health/api` |
| Local | `http://127.0.0.1:5000/api` |

## Authentication

All protected routes require `Authorization: Bearer <JWT>` from `POST /auth/login`.

## CSRF

State-changing requests require `X-CSRF-Token` header matching the `csrf_token` cookie. Fetch via `GET /csrf-token`.

## Core resources

| Resource | Methods | Description |
|----------|---------|-------------|
| `/auth/*` | POST, GET, PUT | Login, profile, password |
| `/patients` | GET, POST | Patient CRUD |
| `/visits` | GET, POST | Visit management |
| `/visits/:id/transcribe` | POST | Queue transcription |
| `/notes/:id` | GET, PUT | Note review and approval |
| `/audio/:visitId` | GET | Authorized audio stream |

## OpenAPI spec

- YAML: `docs/openapi.yaml`
- Live: `GET /api/openapi.yaml`
- Swagger UI: `GET /api/docs`

## Regenerate

Run `powershell -File scripts/fix-api-documentation.ps1 -Force` to refresh the spec scaffold.
'@

Set-FixFileContent -Path (Join-Path $ctx.Workspace 'docs\openapi.yaml') -Content $openApiYaml
Set-FixFileContent -Path (Join-Path $ctx.Workspace 'docs\API.md') -Content $apiMd
Set-FixFileContent -Path (Join-Path $ctx.BackendDir 'src\routes\openapi.js') -Content $swaggerRoute

$openapiPatch = "app.use('/api', require('./routes/openapi'))"
$serverPath = Join-Path $ctx.BackendDir 'src\server.js'
$srv = if (Test-Path $serverPath) { Get-Content $serverPath -Raw } else { '' }
if ($srv -notmatch "require\('./routes/openapi'\)") {
    Invoke-ServerPatch -Marker "require('./routes/openapi')" -InsertAfter '// ─── ROUTES' -PatchBlock $openapiPatch | Out-Null
}

Write-FixReport -Summary 'Created docs/openapi.yaml, docs/API.md, and /api/openapi.yaml route for Swagger integration.' -NextSteps @(
    'Expand openapi.yaml with all route schemas'
    'Install swagger-ui-express for embedded docs if desired'
)

Write-Host ''
Write-Host '[SUCCESS] fix-api-documentation completed' -ForegroundColor Green
