<#
.SYNOPSIS
  ULT audit fix: User consent management table, API, and privacy documentation.

.EXAMPLE
  powershell -File scripts/fix-user-consent.ps1 -Force
#>

[CmdletBinding()]
param([switch]$Force, [switch]$DryRun, [switch]$Rollback)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\fix-common.ps1"
$script:FixForce = $Force
$script:FixDryRun = $DryRun

$ctx = Initialize-FixContext -FixId 'fix-user-consent' -Title 'User Consent Management' `
    -AuditRef 'ULT-0007' -Priority 'HIGH'

if ($Rollback) {
    Write-FixPhase 'ROLLBACK: fix-user-consent'
    Restore-FixBackup -FixId 'fix-user-consent'
    exit 0
}

Write-FixPhase $ctx.Title
Test-RequiredPaths -RequireBackend
if (-not (Confirm-FixStep 'Add user consent table, routes, and privacy policy section?')) { exit 0 }

$migrationSql = @'
-- User consent tracking — generated by fix-user-consent.ps1
CREATE TABLE IF NOT EXISTS user_consents (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  consent_type VARCHAR(64) NOT NULL,
  consent_version VARCHAR(32) NOT NULL,
  granted BOOLEAN NOT NULL DEFAULT false,
  ip_address VARCHAR(64),
  user_agent TEXT,
  granted_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, consent_type, consent_version)
);

CREATE INDEX IF NOT EXISTS idx_user_consents_user ON user_consents (user_id);
CREATE INDEX IF NOT EXISTS idx_user_consents_type ON user_consents (consent_type);
'@

$consentRoute = @'
const express = require('express')
const router = express.Router()
const pool = require('../config/db')
const { protect } = require('../middleware/auth')

const VALID_TYPES = new Set(['privacy_policy', 'terms_of_service', 'phi_processing', 'marketing'])

router.get('/me', protect, async (req, res) => {
  const { rows } = await pool.query(
    'SELECT consent_type, consent_version, granted, granted_at, revoked_at FROM user_consents WHERE user_id = $1 ORDER BY created_at DESC',
    [req.user.id]
  )
  res.json({ consents: rows })
})

router.post('/me', protect, async (req, res) => {
  const { consentType, consentVersion, granted } = req.body || {}
  if (!VALID_TYPES.has(consentType) || !consentVersion) {
    return res.status(400).json({ error: 'Invalid consentType or consentVersion.' })
  }
  const now = granted ? new Date() : null
  const { rows } = await pool.query(
    `INSERT INTO user_consents (user_id, consent_type, consent_version, granted, ip_address, user_agent, granted_at, revoked_at)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
     ON CONFLICT (user_id, consent_type, consent_version)
     DO UPDATE SET granted = EXCLUDED.granted, granted_at = EXCLUDED.granted_at,
                   revoked_at = CASE WHEN EXCLUDED.granted THEN NULL ELSE NOW() END,
                   ip_address = EXCLUDED.ip_address, user_agent = EXCLUDED.user_agent
     RETURNING *`,
    [req.user.id, consentType, consentVersion, !!granted, req.clientIp, req.get('user-agent'), now, granted ? null : new Date()]
  )
  res.json({ consent: rows[0] })
})

module.exports = router
'@

$privacySection = @'
## User Consent Management

Anot Health tracks explicit user consent for:

| Consent type | Purpose |
|--------------|---------|
| privacy_policy | Acceptance of Privacy Policy version |
| terms_of_service | Acceptance of Terms of Service |
| phi_processing | Authorization to process PHI for clinical documentation |
| marketing | Optional marketing communications |

Consent records include version, timestamp, IP address, and user agent for audit purposes.
Users may revoke optional consents via the account settings API (`POST /api/consent/me`).

Data retention: consent records are retained for the life of the account plus 7 years per HIPAA audit requirements.
'@

Set-FixFileContent -Path (Join-Path $ctx.BackendDir 'migrations\20260624_user_consents.sql') -Content $migrationSql
Set-FixFileContent -Path (Join-Path $ctx.BackendDir 'src\routes\consent.js') -Content $consentRoute
Set-FixFileContent -Path (Join-Path $ctx.Workspace 'docs\PRIVACY-POLICY-CONSENT.md') -Content $privacySection

Invoke-ServerPatch -Marker "require('./routes/consent')" -InsertAfter "app.use('/api/support',     require('./routes/support'))" `
    -PatchBlock "app.use('/api/consent',     require('./routes/consent'))"

Write-FixReport -Summary 'Created user_consents table migration, /api/consent routes for recording consent, and privacy policy consent documentation.' -NextSteps @(
    'Apply migration: psql -f migrations/20260624_user_consents.sql'
    'Add consent UI modal on first login'
    'Link PRIVACY-POLICY-CONSENT.md from app footer'
)

Write-Host ''
Write-Host '[SUCCESS] fix-user-consent completed' -ForegroundColor Green
