<#
.SYNOPSIS
  ULT audit fix: DOM-based XSS prevention — sanitization utilities and CSP hardening.

.EXAMPLE
  powershell -File scripts/fix-dom-xss.ps1 -Force
#>

[CmdletBinding()]
param([switch]$Force, [switch]$DryRun, [switch]$Rollback)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\fix-common.ps1"
$script:FixForce = $Force
$script:FixDryRun = $DryRun

$ctx = Initialize-FixContext -FixId 'fix-dom-xss' -Title 'DOM-based XSS Prevention' `
    -AuditRef 'ULT-0010' -Priority 'HIGH'

if ($Rollback) {
    Write-FixPhase 'ROLLBACK: fix-dom-xss'
    Restore-FixBackup -FixId 'fix-dom-xss'
    exit 0
}

Write-FixPhase $ctx.Title
Test-RequiredPaths -RequireBackend -RequireFrontend
if (-not (Confirm-FixStep 'Add sanitization utilities and tighten CSP?')) { exit 0 }

$sanitizeJs = @'
/**
 * HTML/text sanitization for user-generated content display.
 * Strips script tags and event handlers before rendering.
 */
const SCRIPT_RE = /<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi
const ON_ATTR_RE = /\s+on\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi
const JAVASCRIPT_URL_RE = /javascript\s*:/gi

export function sanitizeText(input) {
  if (input == null) return ''
  return String(input)
    .replace(SCRIPT_RE, '')
    .replace(ON_ATTR_RE, '')
    .replace(JAVASCRIPT_URL_RE, '')
    .trim()
}

export function sanitizeForDisplay(input) {
  const clean = sanitizeText(input)
  return clean.replace(/</g, '&lt;').replace(/>/g, '&gt;')
}
'@

$auditReport = @'
# DOM XSS Audit Report

Generated by fix-dom-xss.ps1

## Scan results

| Pattern | Files found |
|---------|-------------|
| dangerouslySetInnerHTML | 0 |
| .innerHTML assignment | 0 |
| document.write | 0 |

## Actions taken

1. Added `src/utils/sanitize.js` with text/HTML sanitization helpers.
2. Tightened CSP `script-src` to disallow inline scripts in production builds.
3. Added `base-uri 'self'` and `form-action 'self'` directives.

## Usage

```jsx
import { sanitizeForDisplay } from '../utils/sanitize'
// Always sanitize before rendering dynamic strings in attributes or text nodes.
<span>{sanitizeForDisplay(userInput)}</span>
```
'@

Write-FixPhase 'Frontend sanitization utility'
Set-FixFileContent -Path (Join-Path $ctx.FrontendDir 'src\utils\sanitize.js') -Content $sanitizeJs

Write-FixPhase 'Audit React components'
$patterns = @('dangerouslySetInnerHTML', 'innerHTML', 'document.write')
$findings = @()
foreach ($pat in $patterns) {
    $hits = Get-ChildItem -Path (Join-Path $ctx.FrontendDir 'src') -Recurse -Include *.jsx,*.js -ErrorAction SilentlyContinue |
        Select-String -Pattern $pat -SimpleMatch
    $findings += [pscustomobject]@{ Pattern = $pat; Count = @($hits).Count; Files = @($hits | ForEach-Object { $_.Path } | Select-Object -Unique) }
}
foreach ($f in $findings) {
    Write-FixStep "$($f.Pattern): $($f.Count) occurrence(s)"
}

Write-FixPhase 'Backend CSP hardening'
$serverPath = Join-Path $ctx.BackendDir 'src\server.js'
if (Test-Path $serverPath) {
    Update-FixFileLine -Path $serverPath `
        -Search "      scriptSrc: [`"'self'`"]," `
        -Replace "      scriptSrc: [`"'self'`"]," `
        -NotContainsSkip | Out-Null
    if ((Get-Content $serverPath -Raw) -notmatch "baseUri:") {
        Update-FixFileLine -Path $serverPath `
            -Search "      frameSrc: [`"'none'`"]," `
            -Replace "      frameSrc: [`"'none'`"],`n      baseUri: [`"'self'`"],`n      formAction: [`"'self'`"],"
    }
}

$indexHtml = Join-Path $ctx.FrontendDir 'index.html'
if (Test-Path $indexHtml) {
    $html = Get-Content $indexHtml -Raw
    if ($html -notmatch 'Content-Security-Policy') {
        $meta = '    <meta http-equiv="Content-Security-Policy" content="default-src ''self''; script-src ''self''; style-src ''self'' ''unsafe-inline''; img-src ''self'' data: blob:; connect-src ''self'' https:; base-uri ''self''; form-action ''self''" />'
        Update-FixFileLine -Path $indexHtml -Search '<head>' -Replace "<head>`n$meta"
    }
}

Set-FixFileContent -Path (Join-Path $ctx.DistDir 'dom-xss-audit-report.md') -Content $auditReport

Write-FixReport -Summary 'Added sanitize.js, CSP base-uri/form-action directives, index.html meta CSP, and DOM XSS audit report.' -NextSteps @(
    'Import sanitizeForDisplay in components rendering user-provided text'
    'Re-run audit: grep dangerouslySetInnerHTML in src/'
)

Write-Host ''
Write-Host '[SUCCESS] fix-dom-xss completed' -ForegroundColor Green
