<#
.SYNOPSIS
  ULT audit fix: Transcription confidence scores — DB column, API, and UI display.

.EXAMPLE
  powershell -File scripts/fix-confidence-scores.ps1 -Force
#>

[CmdletBinding()]
param([switch]$Force, [switch]$DryRun, [switch]$Rollback)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\fix-common.ps1"
$script:FixForce = $Force
$script:FixDryRun = $DryRun

$ctx = Initialize-FixContext -FixId 'fix-confidence-scores' -Title 'Transcription Confidence Scores' `
    -AuditRef 'MEDIUM-CONFIDENCE' -Priority 'MEDIUM'

if ($Rollback) {
    Write-FixPhase 'ROLLBACK: fix-confidence-scores'
    Restore-FixBackup -FixId 'fix-confidence-scores'
    exit 0
}

Write-FixPhase $ctx.Title
Test-RequiredPaths -RequireBackend -RequireFrontend
if (-not (Confirm-FixStep 'Add confidence_score to notes schema, backend parsing, and UI?')) { exit 0 }

$migrationSql = @'
-- Transcription confidence scores — generated by fix-confidence-scores.ps1
ALTER TABLE notes ADD COLUMN IF NOT EXISTS confidence_score NUMERIC(5, 4);
ALTER TABLE notes ADD COLUMN IF NOT EXISTS confidence_scores JSONB;

COMMENT ON COLUMN notes.confidence_score IS 'Overall transcript confidence 0.0000-1.0000 from ASR provider';
COMMENT ON COLUMN notes.confidence_scores IS 'Per-segment confidence array from Deepgram words/channels';
'@

$transcriptionPatch = @'
/**
 * Extract confidence from Deepgram response
 */
function extractConfidence(deepgramResult) {
  const alt = deepgramResult?.results?.channels?.[0]?.alternatives?.[0]
  if (!alt) return { overall: null, segments: [] }
  const overall = typeof alt.confidence === 'number' ? alt.confidence : null
  const segments = (alt.words || []).map((w) => ({
    word: w.word,
    confidence: w.confidence ?? null,
    start: w.start,
    end: w.end,
  }))
  return { overall, segments }
}

module.exports.extractConfidence = extractConfidence
'@

$confidenceUtilFe = @'
/** Format confidence score for display (0-1 -> percentage) */
export function formatConfidence(score) {
  if (score == null || Number.isNaN(Number(score))) return null
  const pct = Math.round(Number(score) * 100)
  return `${pct}%`
}

export function confidenceClass(score) {
  const n = Number(score)
  if (Number.isNaN(n)) return 'confidence-unknown'
  if (n >= 0.9) return 'confidence-high'
  if (n >= 0.75) return 'confidence-medium'
  return 'confidence-low'
}
'@

$confidenceCss = @'
.confidence-badge {
  display: inline-block;
  font-size: 11px;
  font-weight: 600;
  padding: 2px 6px;
  border-radius: 4px;
  margin-left: 6px;
}
.confidence-high { background: #dcfce7; color: #166534; }
.confidence-medium { background: #fef9c3; color: #854d0e; }
.confidence-low { background: #fee2e2; color: #991b1b; }
.confidence-unknown { background: #f3f4f6; color: #6b7280; }
'@

Set-FixFileContent -Path (Join-Path $ctx.BackendDir 'migrations\20260624_confidence_scores.sql') -Content $migrationSql
Set-FixFileContent -Path (Join-Path $ctx.BackendDir 'src\utils\transcriptionConfidence.js') -Content $transcriptionPatch
Set-FixFileContent -Path (Join-Path $ctx.FrontendDir 'src\utils\confidence.js') -Content $confidenceUtilFe
Set-FixFileContent -Path (Join-Path $ctx.FrontendDir 'src\components\confidence.css') -Content $confidenceCss

$confidenceBadgeJsx = @'
import { formatConfidence, confidenceClass } from '../utils/confidence'
import './confidence.css'

/** Displays ASR confidence percentage when available */
export function ConfidenceBadge({ score }) {
  const label = formatConfidence(score)
  if (!label) return null
  return (
    <span
      className={`confidence-badge ${confidenceClass(score)}`}
      title="Transcription confidence"
    >
      {label}
    </span>
  )
}
'@

Set-FixFileContent -Path (Join-Path $ctx.FrontendDir 'src\components\ConfidenceBadge.jsx') -Content $confidenceBadgeJsx

$sharedPath = Join-Path $ctx.FrontendDir 'src\pages\shared.jsx'
if (Test-Path $sharedPath) {
    $shared = Get-Content $sharedPath -Raw
    if ($shared -notmatch 'ConfidenceBadge') {
        $shared = $shared.TrimEnd() + "`n`nexport { ConfidenceBadge } from '../components/ConfidenceBadge'`n"
        Set-FixFileContent -Path $sharedPath -Content $shared -ForceWrite
        Write-FixOk 'Added ConfidenceBadge re-export to shared.jsx'
    } else {
        Write-FixStep 'shared.jsx already references ConfidenceBadge'
    }
}

$transSvcPath = Join-Path $ctx.BackendDir 'src\services\transcriptionService.js'
if (Test-Path $transSvcPath) {
    $ts = Get-Content $transSvcPath -Raw
    if ($ts -notmatch 'extractConfidence') {
        $patched = $false
        if ($ts -match "const axios = require\('axios'\)") {
            Update-FixFileLine -Path $transSvcPath -Search "const axios = require('axios')" `
                -Replace "const axios = require('axios')`nconst { extractConfidence } = require('../utils/transcriptionConfidence')" -NotContainsSkip
            $patched = $true
        }
        if (-not $patched) {
            Update-FixFileLine -Path $transSvcPath `
                -Search "const { loadAiSettings, useDeepgram, defaultRuntimeSettings } = require('./aiSettings')" `
                -Replace "const { extractConfidence } = require('../utils/transcriptionConfidence')`nconst { loadAiSettings, useDeepgram, defaultRuntimeSettings } = require('./aiSettings')" `
                -NotContainsSkip
        }
    }
}

Write-FixReport -Summary 'Added notes.confidence_score/confidence_scores columns, Deepgram confidence extraction utility, ConfidenceBadge UI component, and CSS styling.' -NextSteps @(
    'Apply migration: psql -f migrations/20260624_confidence_scores.sql'
    'Wire extractConfidence into transcription save path in transcriptionService.js'
    'Add <ConfidenceBadge score={note.confidence_score} /> in Scribe/Clinician views'
)

Write-Host ''
Write-Host '[SUCCESS] fix-confidence-scores completed' -ForegroundColor Green
