/** CSRF token helper â€” generated by fix-csrf-protection.ps1 */
let cachedCsrfToken = null

export async function fetchCsrfToken(apiBase) {
  if (cachedCsrfToken) {return cachedCsrfToken}
  const res = await fetch(`${apiBase.replace(/\/+$/, '')}/csrf-token`, { credentials: 'include' })
  if (!res.ok) {throw new Error('Failed to fetch CSRF token')}
  const data = await res.json()
  cachedCsrfToken = data.csrfToken
  return cachedCsrfToken
}

export function clearCsrfToken() {
  cachedCsrfToken = null
}

export function getCsrfHeaders(token) {
  return token ? { 'X-CSRF-Token': token } : {}
}